baseURL = 'https://cestlaz.zamansky.net/'
languageCode = 'en-us'
title = "C'est la Z"


# theme ="hugo-kiera"
theme ="anubis2"

[outputs]
  home = ['html', 'rss']
  section = ['html', 'rss']
  taxonomy = ['html']
  term = ['html']

[outputFormats.RSS]
mediatype='application/rss'
baseName='rss'
pygmentsCodeFences = true
mathjax=true
[pagination]
  pagersize = 3
  path = 'page'

summaryLength =10
enableEmoji = true
pygmentsCodeFences = true

[services]
  [services.disqus]
    shortname = 'cestlaz'

disqusShortname = "cestlaz" #Disqus shortname
commentAutoload = true

googleAnalytics = "" #Google Analytics ID

[params.author]
    name = "Mike Zamansky"           #Author name
    #github = "zamansky"         #Github username
    #gitlab = "zamansky"         #Gitlab username
    #linkedin = "zamansky"       #LinkedIn username
    # facebook = ""       #Facebook username
    # twitter = ""        #Twitter username
    # instagram = ""      #Instagram username
    # stackoverflow = ""  #StackOverflow username
    # devto = ""          #Dev.to username 


[markup.goldmark.renderer]
unsafe = true # true | false; Enable unsafe mode to have a better experience

[markup.highlight]
style = 'base16-snazzy' # Highlight.js style

[params]
    tagline = "Musings of a retired NYC Computer Science Teacher"
    customCSS = []  #Optional Customised CSS
    disableDarkModeCSS = false # disables css style for users using dark-mode
postSections=["post"]
mathjax = true
paginationSinglePost = true
readMore = true
readNextPosts = 2
copyCodeButton = true
rssAsSocialIcon = true
locale = "en-us"
toc = false


social = [
  { id = "bluesky", url = "https://bsky.app/profile/zamansky.bsky.social" },
  { id = "github", url = "https://github.com/zamansky" },
{ id = "gitlab", url = "https://gitlab.com/zamansky" },
  { id = "linkedin", url = "https://www.linkedin.com/in/zamansky" },
#    { id = "email", url = "zamansky@gmail.com"}
]

menu="main"
[menu]
[[menu.main]]
  identifier="home"
  name="home"
  url="/"
  weight=1
[[menu.main]]
  identifier="about"
  name="about"
  url="/about"
  weight=2


[[menu.main]]
identifier="Archive"
name="Archive"
url="/posts/"
  weight=8
[[menu.main]]
identifier="oldblog"
name="Old Blog"
url="https://cestlaz.github.io/cestlaz-old-hugo.github.io"
  weight=8
[[menu.main]]
identifier="roldblog"
name="Really Old Blog"
url="https://cestlaz-nikola.github.io/"
  weight=8
